[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robust-ner"
version = "0.1.0"
dependencies = [
    "torch",
    "transformers>=4.41",
    "datasets>=2.19",
    "evaluate>=0.4",
    "seqeval",
    "pyyaml",
]